### ISSUE TITLE
How nicely does dask play with H2O, PyTorch and TensorFlow?

### ISSUE THREAD

**Issue by dclong** [dask/dask-ml#182]
Dask integrates well with sk-learn and xgboot but what about H2O, PyTorch and TensorFlow?

**Comment by TomAugspurger** [comment]
There's a small tensorflow integration http://dask-ml.readthedocs.io/en/latest/tensorflow.html, but it's relatively immature.

What sort of things are you looking to do?

**Comment by dclong** [comment]
I'm thinking of using Dask to work together with H2O to handle data that is too large to fit into memory of one computer but yet not large enough to go to Spark.

**Comment by TomAugspurger** [comment]
I'm not very familiar with H20, so forgive any naive questions.

If you weren't using Dask, how would you get data to and from H20? Since Dask is just using libraries like pandas and NumPy to do the actual execution, you're often able to take an existing solution and parallelize it with something like `dask.delayed`.

**Comment by TomAugspurger** [comment]
Feel free to post additional questions / results here.
