### ISSUE TITLE
Python 3 only?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#229]
Our default within the Dask subprojects is to support Python 2 and Python 3.  

I'm fine staying with this default, but thought I'd raise the question so that we explicitly make a choice rather than go with tradition without thinking.

**Comment by TomAugspurger** [comment]
I don't have a strong preference here.

Maintaining compatibility with Python 2 is annoying, but not debilitating. PRs like https://github.com/dask/dask-ml/pull/221 are pushing things though, since the syntax is nicer with async / await.

I'm a bit worried about losing users, but I'm not sure how many we have that are Python 2 only.

**Comment by stsievert** [comment]
Can this issue be closed? Dask-ML requires at least Python 3.6: https://github.com/dask/dask-ml/blob/ab6f9cc92aa4938d14ba2ff0d57f0a9fa050fc7b/setup.py#L71

**Comment by jrbourbeau** [comment]
Yep, looks like Python 2 was dropped in https://github.com/dask/dask-ml/pull/500. Thanks for following up @stsievert!
