### ISSUE TITLE
Docs title references version 0.1

### ISSUE THREAD

**Issue by deepyaman** [dask/dask-ml#854]
**What happened**: The title of https://ml.dask.org/ is "Dask-ML — dask-ml 0.1 documentation".

**What you expected to happen**: I would expect it to be "Dask-ML — dask-ml 1.9.0 documentation".

**Anything else we need to know?**: Building the docs locally (following contributing guidelines) results in `<title>Dask-ML &mdash; dask-ml 1.8.1 documentation</title>`. Was trying to debug on CI here: https://github.com/dask/dask-ml/pull/853 (but need workflow access).

**Environment**:

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by jrbourbeau** [comment]
Thanks for reporting @deepyaman. Since the local version of `dask-ml` is controlled by corresponding [git tags](https://github.com/dask/dask-ml/tags), I suspect that the documentation build isn't properly checking out the most recent tags (hence why the version displayed in the documentation is out of date). 

We can check out all git tags in our documentation build by adding

```yaml
  with:
    fetch-depth: 0
```

as mentioned here https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches to this step

https://github.com/dask/dask-ml/blob/f1933bbd344452d8cec900ca902da4e417e1683e/.github/workflows/docs.yaml#L8-L9

in our `github/workflows/docs.yaml` GitHub actions workflow

**Comment by deepyaman** [comment]
@jrbourbeau Thanks, your explanation is very helpful! I've tried pushing your change to the draft PR, just to see if the right version gets captured.

I'm also thinking, it's probably unnecessary to get the history for each tag. Looking at https://github.com/actions/checkout/blob/05e5b94460c9a3b87f066188d19b53f5f6c7fa38/README.md#fetch-all-tags and https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/src/git-command-manager.ts#L171-L197, maybe even `depth=1` would work, but will have to test it out.

**Comment by deepyaman** [comment]
I think have to change the version strategy somehow; looking at https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/version.py and the associated documentation, would need to find some way to indicate that this last version should have been a minor release and not patch, if not storing the version anywhere. @jrbourbeau Do you know if there's such a standard process for `dask-ml`?

**Comment by jrbourbeau** [comment]
Glad to hear it @deepyaman. I think setting `fetch-depth` is the right thing to do to resolve the version being displayed in the docs. 

> I've got <title>Dask-ML &mdash; dask-ml 1.8.1 documentation</title> in the debugging output, matching what I got on my local. Will try and look into this a bit more tomorrow, see why not 1.9.0.

Same here. I think this is because the `1.9.0` tag is attached to this commit https://github.com/dask/dask-ml/commit/05ef365337deb697a89225559760fe4776ab2de1 which isn't on the `main` branch. Perhaps the `1.9.0` tag should be moved to https://github.com/dask/dask-ml/commit/f1933bbd344452d8cec900ca902da4e417e1683e instead. cc @TomAugspurger

**Comment by deepyaman** [comment]
> Same here. I think this is because the `1.9.0` tag is attached to this commit [05ef365](https://github.com/dask/dask-ml/commit/05ef365337deb697a89225559760fe4776ab2de1) which isn't on the `main` branch. Perhaps the `1.9.0` tag should be moved to [f1933bb](https://github.com/dask/dask-ml/commit/f1933bbd344452d8cec900ca902da4e417e1683e) instead. cc @TomAugspurger

@jrbourbeau I tested this on my fork, and it works as expected if the tag is moved to `main` (as you say). Also verified that `fetch-depth: 0` is indeed correct (`fetch-depth: 1` doesn't work). The minor change on #853 should be good to go.
